### ISSUE TITLE
Dependency conflict or missing for libtinfow.so.6

### ISSUE THREAD

**Issue by farleylai** [conda-forge/octave-feedstock#14]
On Ubuntu 16.04, it seems like,

octave-4.2.1 depends on gnuplot-5.2.2 which in turns depends on ncurses-5.9.
However octave-gui depends on libtinfow.so.6 which is available in ncurses-6.x.
Unfortunately, installing ncurses-6.x will remove gnuplot and octave due to the conflict.

So why does conda not detect this dependency conflict?
Is it possible to solve this dependency problem?
Or just wait until the next release?

**Comment by itsallonetome** [comment]
+1  New install gave me gnuplot 5.2.3 (from conda-forge) which causes the same problem, also with the octave package 4.2.1-blas_openblas_6 also from conda-forge.

I don't have nor need octave-gui, unless it's required for the octave_kernel, as I'll only be running octave through jupyter notebooks or the cli.

How to fix?

**Comment by isuruf** [comment]
This is fixed now
