### ISSUE TITLE
Octave seems not to be with Image IO

### ISSUE THREAD

**Issue by TomasKulhanek** [conda-forge/octave-feedstock#18]
Issue:
Octave seems not to be with Image IO. Trying to call `imread(filename)` raises exception:
```
error: imfinfo: support for Image IO was unavailable or disabled when Octave was built
error: called from
    __imread__ at line 80 column 10
    imageIO at line 117 column 26
    imread at line 106 column 30

```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/ccpi/envs/py3:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1  
ace                       6.4.7                         0    paskino
arpack                    3.4.0           blas_openblas_201  [blas_openblas]  conda-forge
asn1crypto                0.24.0                   py35_0  
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
beautifulsoup4            4.6.3                    py35_0  
binutils_impl_linux-64    2.28.1               had2808c_3  
binutils_linux-64         7.2.0               had2808c_27  
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boost                     1.67.0           py35h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.1.23                     0  
cairo                     1.14.6                        5    conda-forge
ccpi-preprocessing        0.10.0           py35h85af7c5_0    ccpi
ccpi-quantification       0.10.0          np113py35h36c6c3e_0    ccpi
ccpi-reconstruction       0.10.0          np113py35h1318013_0    ccpi
ccpi-regulariser          0.10.0          np113py35h9cb2ba8_0    ccpi
ccpi-segmentation         0.10.0           py35hc7959a2_0    ccpi
certifi                   2018.8.24                py35_1  
cffi                      1.11.5           py35he75722e_1  
chardet                   3.0.4                    py35_1  
cil_quantification        0.10.0           py35haf9e448_0    ccpi
cil_reconstruction        0.10.0               h2d77035_0    ccpi
cil_regulariser           0.10.0               h020d0f2_0    ccpi
cil_segmentation          0.10.0               h02cc430_0    ccpi
conda                     4.5.11                   py35_0  
conda-build               3.15.1                   py35_0  
conda-env                 2.6.0                         1  
cryptography              2.3.1            py35hc365091_0  
curl                      7.61.0               h84994c4_0  
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.11.0                        0    conda-forge
decorator                 4.3.2                      py_0    conda-forge
entrypoints               0.2.3                    py35_2    conda-forge
expat                     2.1.0                         3    conda-forge
fftw                      3.3.8             h14c3975_1002    conda-forge
filelock                  3.0.8                    py35_0  
fontconfig                2.12.1                        6    conda-forge
freetype                  2.7                           2    conda-forge
future                    0.16.0                   py35_2    conda-forge
gcc_impl_linux-64         7.2.0                habb00fd_3  
gcc_linux-64              7.2.0               h550dcbe_27  
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
gfortran_impl_linux-64    7.2.0                hdf63c60_3  
gfortran_linux-64         7.2.0               h550dcbe_27  
ghostscript               9.18                          1    bioconda
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.51.4                        0    conda-forge
glob2                     0.6                      py35_0  
glpk                      4.62                          0    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnuplot                   5.0.6                         2    conda-forge
graphicsmagick            1.3.23                        3    bioconda
graphite2                 1.3.13               h23475e2_0  
gsl                       2.2.1           blas_openblas_3  [blas_openblas]  conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
gxx_impl_linux-64         7.2.0                hdf63c60_3  
gxx_linux-64              7.2.0               h550dcbe_27  
h5py                      2.7.1                    py35_1    conda-forge
harfbuzz                  1.4.3                         0    conda-forge
hdf5                      1.8.18                        3    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.7                      py35_0  
intel-openmp              2019.1                      144  
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.0.1            py35h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
itk                       4.13.1                   py35_0    conda-forge
itk-core                  4.13.1.post1             pypi_0    pypi
itk-filtering             4.13.1.post1             pypi_0    pypi
itk-numerics              4.13.1.post1             pypi_0    pypi
itk-registration          4.13.1.post1             pypi_0    pypi
itk-segmentation          4.13.1.post1             pypi_0    pypi
jedi                      0.12.1                   py35_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsoncpp                   1.8.4             h6bb024c_1001    conda-forge
jsonschema                2.6.0                    py35_2    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.34.12                  py35_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
kiwisolver                1.0.1            py35h2d50403_2    conda-forge
libcurl                   7.61.0               h1ad7b7a_0  
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                hd88cf55_4  
libflac                   1.3.1             hf484d3e_1002    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 8.2.0                hdf63c60_1  
libgd                     2.2.5                         2    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libitk                    4.13.0                        0    conda-forge
libogg                    1.3.2             h14c3975_1001    conda-forge
libpng                    1.6.28                        2    conda-forge
libsndfile                1.0.28            hf484d3e_1000    conda-forge
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.7                         1    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.5             h14c3975_1001    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
markupsafe                1.0              py35h470a237_1    conda-forge
matplotlib                2.1.1                    py35_0    conda-forge
metakernel                0.20.14                    py_0    conda-forge
metis                     5.1.0             hf484d3e_1003    conda-forge
mistune                   0.8.3            py35h470a237_2    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.9                    py35_0    conda-forge
mkl_random                1.0.1                    py35_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  5.7.0                    py35_0    conda-forge
numpy                     1.13.3          py35_blas_openblas_200  [blas_openblas]  conda-forge
octave                    4.2.1           blas_openblas_3  [blas_openblas]  conda-forge
octave_kernel             0.28.4                     py_1    conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2p               h14c3975_0  
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.4                        0    conda-forge
parso                     0.3.4                      py_0    conda-forge
patchelf                  0.9                  he6710b0_3  
pcre                      8.39                          0    conda-forge
pexpect                   4.6.0                    py35_0    conda-forge
pickleshare               0.7.5                    py35_0    conda-forge
pip                       10.0.1                   py35_0  
pixman                    0.34.0            h14c3975_1003    conda-forge
pkginfo                   1.4.2                    py35_1  
portaudio                 19                            0  
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.8                      py_0    conda-forge
psutil                    5.4.7            py35h14c3975_0  
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py35_1000    conda-forge
pycosat                   0.6.3            py35h14c3975_0  
pycparser                 2.19                     py35_0  
pygments                  2.3.1                      py_0    conda-forge
pyopenssl                 18.0.0                   py35_0  
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0            py35h8210e8a_7    conda-forge
pysocks                   1.6.8                    py35_0  
python                    3.5.4                         2    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13             py35h14c3975_0  
pyzmq                     17.1.2           py35hae99301_0    conda-forge
qscintilla2               2.9.3            py35hf50527c_3    conda-forge
qt                        5.6.2                         6    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
r                         3.4.1                  r3.4.1_0    conda-forge
r-base                    3.4.1                         2    conda-forge
r-base64enc               0.1_3            r341hc070d10_2    conda-forge
r-boot                    1.3_20                   r341_0    conda-forge
r-checkpoint              0.4.3                  r3.4.1_0    conda-forge
r-class                   7.3_14           r341hc070d10_2    conda-forge
r-cluster                 2.0.7_1          r341h364d78e_0    conda-forge
r-codetools               0.2_15           r341h6115d3f_1    conda-forge
r-crayon                  1.3.4            r341h6115d3f_1    conda-forge
r-curl                    3.2              r341hc070d10_2    conda-forge
r-digest                  0.6.18           r341hc070d10_0    conda-forge
r-doparallel              1.0.11           r341h6115d3f_1    conda-forge
r-evaluate                0.11             r341h6115d3f_0    conda-forge
r-foreach                 1.4.4            r341h6115d3f_1    conda-forge
r-foreign                 0.8_71           r341hc070d10_2    conda-forge
r-glue                    1.3.0            r341h470a237_2    conda-forge
r-htmltools               0.3.6            r341hfc679d8_2    conda-forge
r-irdisplay               0.6.2                    r341_0    conda-forge
r-irkernel                0.8.14                   r341_0    conda-forge
r-iterators               1.0.10           r341h6115d3f_1    conda-forge
r-jsonlite                1.5              r341hc070d10_2    conda-forge
r-kernsmooth              2.23_15          r341h364d78e_2    conda-forge
r-lattice                 0.20_35          r341hc070d10_0    conda-forge
r-magrittr                1.5              r341h6115d3f_1    conda-forge
r-mass                    7.3_50           r341hc070d10_2    conda-forge
r-matrix                  1.2_14           r341hc070d10_2    conda-forge
r-mgcv                    1.8_24           r341hc070d10_2    conda-forge
r-nlme                    3.1_137          r341h364d78e_0    conda-forge
r-nnet                    7.3_12           r341hc070d10_2    conda-forge
r-pbdzmq                  0.3_2                  r3.4.1_0    conda-forge
r-png                     0.1_7            r341hc070d10_2    conda-forge
r-r6                      2.2.2            r341h6115d3f_1    conda-forge
r-rcpp                    1.0.0            r341h9d2a408_0    conda-forge
r-recommended             3.4.1                  r3.4.1_0    conda-forge
r-repr                    0.17                     r341_0    conda-forge
r-rpart                   4.1_13           r341hc070d10_2    conda-forge
r-runit                   0.4.32           r341h6115d3f_0    conda-forge
r-spatial                 7.3_11           r341hc070d10_2    conda-forge
r-stringi                 1.2.4            r341h9d2a408_1    conda-forge
r-stringr                 1.3.1            r341h6115d3f_1    conda-forge
r-survival                2.42_6           r341hc070d10_1    conda-forge
r-uuid                    0.1_2            r341hc070d10_1    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.19.1                   py35_0  
ruamel_yaml               0.15.46          py35h14c3975_0  
scipy                     0.19.1          py35_blas_openblas_202  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1           py35hfc679d8_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
suitesparse               4.5.4           blas_openblas_200  [blas_openblas]  conda-forge
tbb                       2019.3            h6bb024c_1000    conda-forge
terminado                 0.8.1                    py35_1    conda-forge
testpath                  0.3.1                    py35_1    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   5.1.1            py35h470a237_0    conda-forge
tqdm                      4.29.1                     py_0  
traitlets                 4.3.2                    py35_0    conda-forge
urllib3                   1.23                     py35_0  
vtk                       8.1.0                  py35_200    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.31.1                   py35_0  
widgetsnbextension        3.4.2                    py35_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               h7b6447c_3   
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : py3
    active env location : /opt/ccpi/envs/py3
            shell level : 1
       user config file : /home/vagrant/.condarc
 populated config files : 
          conda version : 4.6.3
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /opt/ccpi  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/ccpi/pkgs
                          /home/vagrant/.conda/pkgs
       envs directories : /opt/ccpi/envs
                          /home/vagrant/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.3 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-862.11.6.el7.x86_64 scientific/7.6 glibc/2.17
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by isuruf** [comment]
Can you update your octave package? Latest build is `octave-4.2.1-blas_openblash5b47107_8`

**Comment by TomasKulhanek** [comment]
Cannot test on the updated to octave-4.2.1-blas_openblash5b47107_8 
May be due to other dependencies - octave fails to start. Tried fresh installation with jupyter and octave-4.2.1-blas_openblash5b47107_8 and it fails, but this is different error

error `octave`
<details>
(py3) [vagrant@localhost log]$ octave
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
octave exited with signal 6
</details>

`conda list`
<detail>
(py3) [vagrant@localhost log]$ conda list
# packages in environment at /opt/ccpi/envs/py3:
#
# Name                    Version                   Build  Channel
alsa-lib                  1.1.5             h14c3975_1000    conda-forge
arpack                    3.6.3           blas_openblash6d6ea35_1002  [blas_openblas]  conda-forge
atk                       2.25.90           hb9dd440_1002    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
chrpath                   0.16              h14c3975_1001    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.3.2                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fasteners                 0.14.1                   pypi_0    pypi
fftw                      3.3.8             h14c3975_1002    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
ghostscript               9.22              hf484d3e_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.58.2            hf63aee3_1001    conda-forge
glpk                      4.65              ha14ba45_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnuplot                   5.2.6                hdfabf6f_0    conda-forge
gobject-introspection     1.58.2          py37h2da5eee_1000    conda-forge
graphicsmagick            1.3.31               h437c9d9_2    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
harfbuzz                  2.3.1                h6824563_0    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
ipykernel                 5.1.0           py37h24bf2e0_1002    conda-forge
ipython                   7.2.0           py37h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.2                py37_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.0a3               py37_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.16.2            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libflac                   1.3.1             hf484d3e_1002    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgd                     2.2.5             h0d07dcb_1005    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libogg                    1.3.2             h14c3975_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libsndfile                1.0.28            hf484d3e_1000    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.5             h14c3975_1001    conda-forge
libwebp                   1.0.2                h576950b_1    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
markdown                  3.0.1                    pypi_0    pypi
markupsafe                1.1.0           py37h14c3975_1000    conda-forge
metakernel                0.20.14                    py_0    conda-forge
metis                     5.1.0             hf484d3e_1003    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
monotonic                 1.5                      pypi_0    pypi
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  he6710b0_1  
networkx                  2.2                      pypi_0    pypi
notebook                  5.7.4                 py37_1000    conda-forge
numpy                     1.16.1                   pypi_0    pypi
octave                    4.2.1           blas_openblash5b47107_8  [blas_openblas]  conda-forge
octave_kernel             0.28.4                     py_1    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pandas                    0.24.1                   pypi_0    pypi
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
parso                     0.3.4                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.0.2                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
portaudio                 19.6.0               hf484d3e_2    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.8                      py_0    conda-forge
psutil                    5.5.0                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
pydot                     1.4.1                    pypi_0    pypi
pydotplus                 2.0.2                    pypi_0    pypi
pygments                  2.3.1                      py_0    conda-forge
pyparsing                 2.3.1                    pypi_0    pypi
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pyrsistent                0.14.10          py37h14c3975_0    conda-forge
python                    3.7.1             hd21baee_1000    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                   pypi_0    pypi
pyyaml                    3.13                     pypi_0    pypi
pyzmq                     17.1.2          py37h6afc9c9_1001    conda-forge
qhull                     2015.2            h6bb024c_1000    conda-forge
qscintilla2               2.9.3           py37h982f88c_1003    conda-forge
qt                        5.6.2             hce4f676_1013    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
readline                  7.0                  h7b6447c_5  
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sos                       0.18.7                   pypi_0    pypi
sos-notebook              0.18.5                   pypi_0    pypi
sqlite                    3.26.0               h7b6447c_0  
suitesparse               4.5.6           blas_openblash17e8c26_1201  [blas_openblas]  conda-forge
tabulate                  0.8.3                    pypi_0    pypi
tbb                       2019.3            h6bb024c_1000    conda-forge
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                 py37_1000    conda-forge
tk                        8.6.8                hbc83047_0  
tornado                   5.1.1           py37h14c3975_1000    conda-forge
tqdm                      4.31.1                   pypi_0    pypi
traitlets                 4.3.2                 py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.0                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xxhash                    1.3.0                    pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zlib                      1.2.11               h7b6447c_3 
</detail>

**Comment by isuruf** [comment]
Can you debug and see which package raises that error?

**Comment by TomasKulhanek** [comment]
I don't know how to debug.

Prepared Vagrant config to reproduce the issue on clean Scientific Linux 7 at gist https://gist.github.com/TomasKulhanek/90a3d214a2f682778243495e01ca616a

In order to reproduce, save the above link to `Vagrantfile` and in command line launch `vagrant up`. After `vagrant ssh` launch `octave`.
This will produce error
```
(py3) [vagrant@localhost ~]$ octave
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

**Comment by isuruf** [comment]
Please try the latest build and if it doesn't work, re-open this issue.

**Comment by JohnHerry** [comment]
The same error. CentOS7, GraphicMagick and octave are built by hand, because the default yum installed octave was too old to install the image package. But the result octave can not do image IO, error info just like follows:

`support for Image IO was unavailable or disabled when Octave was built  
error: called from
    __imread__ at line 80 column 10
    imageIO at line 118 column 28
    imread at line 106 column 33
`
My octave version is 5.1.0

**Comment by isuruf** [comment]
If you built octave by hand, how is that related to conda-forge?
