### ISSUE TITLE
Release versions for 4.2.2, 4.4.0, 4.4.1, 5.1.0

### ISSUE THREAD

**Issue by moorepants** [conda-forge/octave-feedstock#33]
Issue:

There have been 3 minor updates and 1 major update to Octave. It would be great if the conda-forge packages for these could be generated.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by izahn** [comment]
With the release of octave 6.1 in November 2020 we are now two major versions behind. Is help needed to maintain this package?

**Comment by moorepants** [comment]
> Is help needed to maintain this package?

I'm sure help would be more than appreciated.
