### ISSUE TITLE
Basic octave commands do not seem to work

### ISSUE THREAD

**Issue by moorepants** [conda-forge/octave-feedstock#35]
Issue:
```
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ which octave
/opt/conda/bin/octave
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ which octave-cli
/opt/conda/bin/octave-cli
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ which conda
/opt/conda/bin/conda
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ conda list octave
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
octave                    4.2.1               h7337af8_13    conda-forge
octave_kernel             0.31.0                     py_0    conda-forge
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ octave-cli
GNU Octave, version 4.2.1
Copyright (C) 2017 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> display('a')
error: 'display' undefined near line 1 column 1
octave:1> version()
error: 'version' undefined near line 1 column 1
octave:1> 1 + 1
ans =  2
octave:2> help ode45
error: 'help' undefined near line 1 column 1
octave:2> help sum
error: 'help' undefined near line 1 column 1
octave:2> sum(1, 2)
ans =  1
octave:3> exit
```
It doesn't seem like all the functions are present.
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ conda list octave
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
octave                    4.2.1               h7337af8_13    conda-forge
octave_kernel             0.31.0                     py_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ conda info

     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.6.7.final.0
       virtual packages : 
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.6.7 Linux/4.15.0-50-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:0
             netrc file : None
           offline mode : False
```
</details>

**Comment by isuruf** [comment]
Have you activated the conda environment?

**Comment by isuruf** [comment]
I can reproduce this when the conda environment is not activated. Please follow the instructions at https://github.com/conda-forge/octave-feedstock/issues/31

**Comment by moorepants** [comment]
I was using the root conda environment.

**Comment by moorepants** [comment]
In the other thread you suggest activating the environment, but in this one I am using octave from the root conda environment. So, it isn't clear what to do.

**Comment by isuruf** [comment]
You still need to activate the root conda environment.

**Comment by isuruf** [comment]
`conda activate` or `source activate`

**Comment by moorepants** [comment]
I've never activated a root conda environment and have used conda since it came out. This is on a jupyterhub installation where i want Octave to work for all users when they log in without running any special commands. I don't have to activate the root enironment to use any other software. Is this something that needs to be fixed in this feedstock?

**Comment by isuruf** [comment]
> This is on a jupyterhub installation where i want Octave to work for all users when they log in without running any special commands.

The admin has to activate the environment before starting the jupyterhub installation. Not the users.

> I don't have to activate the root enironment to use any other software. Is this something that needs to be fixed in this feedstock?

You are welcome to try and send a PR. Octave hard codes the paths of some tools in the binaries and conda's binary replacement logic doesn't work. Therefore, binary replacement was removed and OCTAVE_HOME is added as an activation script which gets run when you activate the conda environment.

> I've never activated a root conda environment and have used conda since it came out.

AFAIK, not activating the root (or any) conda environment is not officially supported.

**Comment by moorepants** [comment]
> You are welcome to try and send a PR. Octave hard codes the paths of some tools in the binaries and conda's binary replacement logic doesn't work.

Ah, so this is a unique situation. That explains things.

> AFAIK, not activating the root (or any) conda environment is not officially supported.

I thought that conda simply mucked with the path when you add the startup scripts to your terminal's rc files, not that `source activate root` was ever called. Not really sure though, as this has seemed to change over the years. But it is clear that this octave package doesn't seem to behave the same as other packages I install via conda.
