### ISSUE TITLE
Mac package

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/octave-feedstock#4]
Would be pretty cool to be able to install Octave from conda-forge. Then again, I have no idea what obstacles this might face.

**Comment by isuruf** [comment]
See https://github.com/conda-forge/octave-feedstock/pull/1
Need somebody with access to OSX to debug it.

**Comment by jakirkham** [comment]
Looks like it is timing out. Though it appears to be in some sort of loop. 😕 Best guess is it has something to do with the prefix length. Do any of the dependencies have a short prefix?

**Comment by isuruf** [comment]
No, I checked and everything has long prefixes.

**Comment by jakirkham** [comment]
Hmm. So it seems `portaudio` and `qt` are coming from `defaults`. Are we sure they both have long prefixes? Just double checking as those stick out to me. Also a little weird that `qt` is coming from `defaults`. Any idea why that is happening?

**Comment by isuruf** [comment]
I guess we should try for a `portaudio` package in `conda-forge`. `qt` is pulled from defaults because we are using `qt 4.8.*` here and `conda-forge` package is in a different label.

**Comment by isuruf** [comment]
It's the qt package from defaults that's the issue here. Can you move the following package to the main label ?
https://anaconda.org/conda-forge/qt/4.8.7/download/osx-64/qt-4.8.7-7.tar.bz2

**Comment by isuruf** [comment]
@conda-forge/qt, is the qt 4.8.7 package on `conda-forge` still being tested or is it ready to be moved into main channel?

**Comment by ocefpaf** [comment]
Do we have a `4.8.7` in https://anaconda.org/conda-forge/pyqt/files ?

**Comment by isuruf** [comment]
Ah, nope. Is that the reason qt-4.8.7 for osx is in test channel?

**Comment by ocefpaf** [comment]
> Ah, nope. Is that the reason qt-4.8.7 for osx is in test channel?

Not sure. I lost track of the OS X qt packages b/c we never got a volunteer to build it I guess. Things are peachy on Windows and Linux though :wink:

**Comment by isuruf** [comment]
OSX packages are working with qt5, so I'm going to close this. If anybody needs qt4, they can reopen this issue.

**Comment by ocefpaf** [comment]
Thanks @isuruf!
