### ISSUE TITLE
help maintenance?

### ISSUE THREAD

**Issue by ngam** [conda-forge/octave-feedstock#58]
Hi @conda-forge/octave 

Do you need help maintenance? I am happy to volunteer --- and I also would like to add support for osx-arm64 soon if possible (added it to the migrations).

Let me know, thanks!

@isuruf
@ocefpaf

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ngam** [comment]
@izahn any idea why there's been silence on here recently --- Do you have an interest in helping maintaining this and adding the arm-osx support (for which the bot is coming shortly) lol

**Comment by ngam** [comment]
Is there something fundamentally wrong? It doesn't look like it!

**Comment by izahn** [comment]
I think just the same old story of maintainers starting to lose interest. It would be good to have more maintainers for this recipe, I am interested in that. Happy to help with the arm-osx stuff if I can, though I don't have much experience with it.

**Comment by ngam** [comment]
Sounds good! I don't know what the process is like, and I have this newfound energy to help and volunteer, so I am happy to do a lot of the maintenance work where needed (e.g. sometimes it is as simple as just automerging stuff, which I am happy to do). It's not like one of those crazy (tensorflow, pytorch) packages where a lot of rigorous work is needed... 


Should I basically make a pull request to add myself? Or should I wait for the maintainers to see this at some point?

**Comment by ngam** [comment]
I think, credit to the maintainers, this is a very well designed build that it shouldn't be too hard to migrate it to osx-arm... but we will see when the helpful bot is here 😉

**Comment by izahn** [comment]
Cool, I think the osx-arm migration can be a good opportunity for you to get involved. If there are any issues with it you can for the PR from the bot, fix it, and submit it as another PR.
