### ISSUE TITLE
GTK issues in Ubuntu 17.10 workaround

### ISSUE THREAD

**Issue by bbevan** [conda-forge/octave-feedstock#8]
I'm running Ubuntu 17.10. When I tried to run octave for the first time, I received an error related to gtk.

$ octave
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant

What I had to do was chown the ~/.config/octave directory to the non-root user I use.

The fix was

$ sudo chown -R username /home/username/.config/octave/

It now runs fine as the non-root user and even loads the gui.

**Comment by isuruf** [comment]
Anything under `/home/username/` should belong to the user. Did you run octave using root?

**Comment by bbevan** [comment]
I tried to reinstall with the following commands.

$ conda create -n conda-forge
$ source activate conda-forge
$ conda install octave

$ source activate conda-forge
$ octave
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant

It still doesn't work without the workaround. It may be that /home/username/.config/ belongs to root in Ubuntu.

Thanks!

**Comment by isuruf** [comment]
In Ubuntu 16.04 it belongs to the user. Something must have messed up the permissions in you home directory.
```
drwx------ 32 isuru isuru    4096 ඔක්   20 17:33 .config
```

**Comment by matteotanca** [comment]
I think it's a ubuntu theme related problem, I have the same error doing an apt update for example.

**Comment by bbevan** [comment]
Thanks for clarifying, Matteo!

-Brandon

**Comment by vkarne** [comment]
When I am trying to run skype on ubuntu 17.10, I too got the error as below and skype could not launched:
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
need help

**Comment by amineHY** [comment]
I get the same issue when I want to launch my application, 
This the error I get : 
--------------------------------------------------
HP-ZBook-15-G2:~$ superproductivity 
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
module.js:472



Any help please ?.

**Comment by isuruf** [comment]
@vkarne, @amineHY, this is not a ubuntu support forum. Please raise this issue in an ubuntu forum.

**Comment by isuruf** [comment]
@bbevan, I'm closing this as it seems unrelated to conda-forge. Please reopen this issue if you think it's not.
